// Extracts every comment from the rule packages under .lintcn/ into one
// markdown file and removes it from the source. Uses go/parser rather than a
// line scan so that a `//` inside a Go string literal -- the TypeScript
// fixtures in the test tables contain one -- is never mistaken for a comment.
//
// `// lintcn:` directives are kept: lintcn's discovery reads a rule's name,
// severity and description out of them by regex before compiling, so removing
// them unregisters the rule with no error.
package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var directive = regexp.MustCompile(`^//\s*(lintcn:|go:|nolint)`)

type file struct {
	path     string
	pkg      string
	groups   []group
	lines    int
	comments int
}

type group struct {
	line       int
	text       string
	start, end int
	inline     bool
	kept       bool
}

func main() {
	root, out := os.Args[1], os.Args[2]

	entries, err := os.ReadDir(root)
	if err != nil {
		panic(err)
	}

	var files []file
	fset := token.NewFileSet()

	for _, dir := range entries {
		if !dir.IsDir() || strings.HasPrefix(dir.Name(), ".") {
			continue
		}
		goFiles, _ := filepath.Glob(filepath.Join(root, dir.Name(), "*.go"))
		sort.Strings(goFiles)

		for _, path := range goFiles {
			src, err := os.ReadFile(path)
			if err != nil {
				panic(err)
			}
			parsed, err := parser.ParseFile(fset, path, src, parser.ParseComments)
			if err != nil {
				panic(err)
			}

			f := file{path: path, pkg: parsed.Name.Name, lines: strings.Count(string(src), "\n") + 1}
			srcLines := strings.Split(string(src), "\n")

			for _, cg := range parsed.Comments {
				pos, endPos := fset.Position(cg.Pos()), fset.Position(cg.End())
				g := group{
					line:  pos.Line,
					text:  cg.Text(),
					start: pos.Offset,
					end:   endPos.Offset,
					kept:  directive.MatchString(string(src[pos.Offset:endPos.Offset])),
				}
				if pos.Line-1 < len(srcLines) {
					g.inline = strings.TrimSpace(srcLines[pos.Line-1][:pos.Column-1]) != ""
				}
				f.groups = append(f.groups, g)
				f.comments += strings.Count(strings.TrimRight(g.text, "\n"), "\n") + 1
			}

			if err := os.WriteFile(path, strip(src, f.groups), 0o644); err != nil {
				panic(err)
			}
			files = append(files, f)
		}
	}

	report(files, root, out)
}

// strip removes each non-directive comment group, taking the whole line with
// it when the comment is all that line holds.
func strip(src []byte, groups []group) []byte {
	out := src
	for i := len(groups) - 1; i >= 0; i-- {
		g := groups[i]
		if g.kept {
			continue
		}
		start, end := g.start, g.end
		lineStart := 0
		if n := strings.LastIndexByte(string(out[:start]), '\n'); n >= 0 {
			lineStart = n + 1
		}
		lineEnd := len(out)
		if n := strings.IndexByte(string(out[end:]), '\n'); n >= 0 {
			lineEnd = end + n
		}
		if blank(out[lineStart:start]) && blank(out[end:lineEnd]) {
			start, end = lineStart, min(lineEnd+1, len(out))
		} else {
			for start > 0 && (out[start-1] == ' ' || out[start-1] == '\t') {
				start--
			}
		}
		out = append(out[:start:start], out[end:]...)
	}
	return out
}

func blank(b []byte) bool { return strings.TrimSpace(string(b)) == "" }

func report(files []file, root, out string) {
	var b strings.Builder
	removed, kept, totalL := 0, 0, 0
	for _, f := range files {
		totalL += f.lines
		for _, g := range f.groups {
			n := strings.Count(strings.TrimRight(g.text, "\n"), "\n") + 1
			if g.kept {
				kept += n
			} else {
				removed += n
			}
		}
	}

	fmt.Fprintf(&b, "# Every comment removed from the rule packages\n\n")
	fmt.Fprintf(&b, "Generated by `tools/comments` from `%s`. The comments below no longer\n"+
		"exist in the source; this file is the record of them.\n\n", root)
	fmt.Fprintf(&b, "%d comment lines removed from %d files (%d lines of Go). %d lines of\n"+
		"`// lintcn:` metadata were kept -- lintcn's discovery reads them by regex.\n\n",
		removed, len(files), totalL, kept)

	fmt.Fprintf(&b, "| Package | File | Groups | Comment lines | %% of file |\n|---|---|---:|---:|---:|\n")
	for _, f := range files {
		fmt.Fprintf(&b, "| `%s` | `%s` | %d | %d | %.0f%% |\n", f.pkg, filepath.Base(f.path),
			len(f.groups), f.comments, 100*float64(f.comments)/float64(f.lines))
	}
	b.WriteString("\n---\n")

	for _, f := range files {
		rel, _ := filepath.Rel(filepath.Dir(root), f.path)
		fmt.Fprintf(&b, "\n## `%s`\n\n", rel)
		if len(f.groups) == 0 {
			b.WriteString("_No comments._\n")
			continue
		}
		for _, g := range f.groups {
			kind := ""
			if g.inline {
				kind = " _(inline)_"
			}
			if g.kept {
				kind += " _(kept in source)_"
			}
			fmt.Fprintf(&b, "**L%d**%s\n", g.line, kind)
			for _, line := range strings.Split(strings.TrimRight(g.text, "\n"), "\n") {
				fmt.Fprintf(&b, "> %s\n", line)
			}
			b.WriteString("\n")
		}
	}

	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("removed %d comment lines, kept %d directive lines, %d files -> %s\n",
		removed, kept, len(files), out)
}
